var bestAlbumsByGenre = []
bestAlbumsByGenre[0] = "Country";
bestAlbumsByGenre[0][0] = "JohnnyCash:Live at Folsom Prison"
bestAlbumsByGenre[0][01] = "PatsyCline:Sentimentally Yours";
bestAlbumsByGenre[0][2] = "HankWilliams:I'm Blue Inside";
bestAlbumsByGenre[1] = "Rock";
bestAlbumsByGenre[1][0] = "T-Rex:Slider";
bestAlbumsByGenre[1][1] = "Nirvana:Nevermind";
bestAlbumsByGenre[1][2] = "Lou Reed:Tranformer";
bestAlbumsByGenre[2] = "Punk";
bestAlbumsByGenre[2][0] = "Flipper:Generic";
bestAlbumsByGenre[2][1] = "TheDeadMilkmen:Big Lizard in my Backyard";
bestAlbumsByGenre[2][2] = "PattiSmith:Easter";